server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/keycloak}
  redis:
    host: ${REDIS_URL:localhost}
    port: 6379




logging:
  level:
    org:
      springframework:
        transaction: ${IS_LOGGING_LEVEL:DEBUG}
        security: ${IS_LOGGING_LEVEL:DEBUG}
        web: ${IS_LOGGING_LEVEL:DEBUG}